spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/visa_bot
    username: visa_bot
    password: AmericanPie13###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  bot:
    username: visa_best_helper_bot
    token: 8031980944:AAEqD8ECIRooxYfHxWu5t45qUoE9dnBF5SM
