spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visa_bot
    username: visa_bot
    password: visa_bot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  bot:
    username: YOUR_BOT_USERNAME
    token: YOUR_BOT_TOKEN
