spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/visa_bot}
    username: ${SPRING_DATASOURCE_USERNAME:visa_bot}
    password: ${SPRING_DATASOURCE_PASSWORD:visa_bot}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:your_local_bot_username}
    token: ${TELEGRAM_BOT_TOKEN:your_local_bot_token}
